apiVersion: apps/v1
kind: Deployment
metadata:
  name: techdome-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techdome-backend
  template:
    metadata:
      labels:
        app: techdome-backend
    spec:
      containers:
      - name: techdome-backend
        image: hackur/backendo:latest
        env:
          - name: DB_HOST
            value: "postgres"   # Matches the PostgreSQL service name
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "NewPassword1234"
          - name: DB_NAME
            value: "Techdome-DB"
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: techdome-backend
spec:
  type: ClusterIP
  selector:
    app: techdome-backend
  ports:
    - port: 5000
      targetPort: 5000
