apiVersion: apps/v1
kind: Deployment
metadata:
  name: techdome-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techdome-frontend
  template:
    metadata:
      labels:
        app: techdome-frontend
    spec:
      containers:
      - name: techdome-frontend
        image: hackur/frontend:latest
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: techdome-frontend
spec:
  type: LoadBalancer
  selector:
    app: Techdome-frontend
  ports:
    - port: 3000
      targetPort: 3000
